### ISSUE TITLE
Distribution Group Bug/Enhancements

### ISSUE THREAD

**Issue by matt020191** [KnowMoreIT/CloudPanel#64]
- You can add distribution groups to other distribution groups, but you do not have the ability to add mail contacts or security groups
- Ability to leave the "Managed by" list empty without a 500 error being thrown, and a default single user being added (for example, in EAC, this is the built-in Administrator account)
- If the "Messages sent to this group have to be approved by a moderator" is unchecked, it still throws an error saying that one of the three radio buttons needs to be selected

**Comment by KnowMoreIT** [comment]
This is resolved now
